INSERT INTO PUBLIC.RATINGS (RATING_NAME) SELECT 'G'
WHERE NOT EXISTS (SELECT RATING_NAME FROM RATINGS WHERE RATING_NAME = 'G');
INSERT INTO PUBLIC.RATINGS (RATING_NAME) SELECT 'PG'
WHERE NOT EXISTS (SELECT RATING_NAME FROM RATINGS WHERE RATING_NAME = 'PG');
INSERT INTO PUBLIC.RATINGS (RATING_NAME) SELECT 'PG-13'
WHERE NOT EXISTS (SELECT RATING_NAME FROM RATINGS WHERE RATING_NAME = 'PG-13');
INSERT INTO PUBLIC.RATINGS (RATING_NAME) SELECT 'R'
WHERE NOT EXISTS (SELECT RATING_NAME FROM RATINGS WHERE RATING_NAME = 'R');
INSERT INTO PUBLIC.RATINGS (RATING_NAME) SELECT 'NC-17'
WHERE NOT EXISTS (SELECT RATING_NAME FROM RATINGS WHERE RATING_NAME = 'NC-17');

INSERT INTO PUBLIC.GENRES (GENRE_NAME) SELECT 'Комедия'
WHERE NOT EXISTS (SELECT GENRE_NAME FROM GENRES WHERE GENRE_NAME = 'Комедия');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) SELECT 'Драма'
WHERE NOT EXISTS (SELECT GENRE_NAME FROM GENRES WHERE GENRE_NAME = 'Драма');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) SELECT 'Мультфильм'
WHERE NOT EXISTS (SELECT GENRE_NAME FROM GENRES WHERE GENRE_NAME = 'Мультфильм');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) SELECT 'Триллер'
WHERE NOT EXISTS (SELECT GENRE_NAME FROM GENRES WHERE GENRE_NAME = 'Триллер');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) SELECT 'Документальный'
WHERE NOT EXISTS (SELECT GENRE_NAME FROM GENRES WHERE GENRE_NAME = 'Документальный');
INSERT INTO PUBLIC.GENRES (GENRE_NAME) SELECT 'Боевик'
WHERE NOT EXISTS (SELECT GENRE_NAME FROM GENRES WHERE GENRE_NAME = 'Боевик');