INSERT INTO PUBLIC.USERS (USER_EMAIL, USER_LOGIN, USER_NAME, BIRTHDAY)
VALUES ('email1@test.com', 'login1', 'name1', '2022-10-01');

INSERT INTO PUBLIC.USERS (USER_EMAIL, USER_LOGIN, USER_NAME, BIRTHDAY)
VALUES ('email2@test.com', 'login2', 'name2', '2022-10-01');

INSERT INTO PUBLIC.USERS (USER_EMAIL, USER_LOGIN, USER_NAME, BIRTHDAY)
VALUES ('email3@test.com', 'login3', 'name3', '2022-10-01');

INSERT INTO PUBLIC.DIRECTORS (DIRECTOR_NAME)
VALUES ('Director 1');

INSERT INTO PUBLIC.FILMS (FILM_NAME, FILM_DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('film1', 'description1', '2022-10-03', 120, 1);

INSERT INTO PUBLIC.DIRECTORS_FILMS (FILM_ID, DIRECTOR_ID)
VALUES (1, 1);

INSERT INTO PUBLIC.FILMS (FILM_NAME, FILM_DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('film2', 'description2', '2022-10-02', 120, 2);

INSERT INTO PUBLIC.DIRECTORS_FILMS (FILM_ID, DIRECTOR_ID)
VALUES (2, 1);

INSERT INTO PUBLIC.FILMS (FILM_NAME, FILM_DESCRIPTION, RELEASE_DATE, DURATION, RATING_ID)
VALUES ('film3', 'description3', '2022-10-01', 120, 3);

INSERT INTO PUBLIC.DIRECTORS_FILMS (FILM_ID, DIRECTOR_ID)
VALUES (3, 1);

INSERT INTO PUBLIC.LIKES (USER_ID, FILM_ID)
VALUES (1, 3);

INSERT INTO PUBLIC.LIKES (USER_ID, FILM_ID)
VALUES (2, 2);

INSERT INTO PUBLIC.LIKES (USER_ID, FILM_ID)
VALUES (2, 3);

INSERT INTO PUBLIC.LIKES (USER_ID, FILM_ID)
VALUES (3, 1);

INSERT INTO PUBLIC.LIKES (USER_ID, FILM_ID)
VALUES (3, 2);

INSERT INTO PUBLIC.LIKES (USER_ID, FILM_ID)
VALUES (3, 3);

INSERT INTO PUBLIC.GENRES_FILMS (FILM_ID, GENRE_ID)
VALUES (1, 1);

INSERT INTO PUBLIC.GENRES_FILMS (FILM_ID, GENRE_ID)
VALUES (1, 2);

INSERT INTO PUBLIC.GENRES_FILMS (FILM_ID, GENRE_ID)
VALUES (1, 3);

INSERT INTO PUBLIC.GENRES_FILMS (FILM_ID, GENRE_ID)
VALUES (1, 4);

INSERT INTO PUBLIC.GENRES_FILMS (FILM_ID, GENRE_ID)
VALUES (1, 5);

INSERT INTO PUBLIC.GENRES_FILMS (FILM_ID, GENRE_ID)
VALUES (1, 6);

INSERT INTO PUBLIC.GENRES_FILMS (FILM_ID, GENRE_ID)
VALUES (2, 1);

INSERT INTO PUBLIC.GENRES_FILMS (FILM_ID, GENRE_ID)
VALUES (3, 1);

INSERT INTO PUBLIC.GENRES_FILMS (FILM_ID, GENRE_ID)
VALUES (3, 2);

INSERT INTO PUBLIC.FRIENDS (USER_ID, FRIEND_ID, CONFIRMED)
VALUES (1, 2, TRUE);

INSERT INTO PUBLIC.FRIENDS (USER_ID, FRIEND_ID, CONFIRMED)
VALUES (2, 1, TRUE);

INSERT INTO PUBLIC.FRIENDS (USER_ID, FRIEND_ID, CONFIRMED)
VALUES (1, 3, DEFAULT);

INSERT INTO PUBLIC.REVIEWS (CONTENT, IS_POSITIVE, USER_ID, FILM_ID)
VALUES ('Very good review', true, 1, 1);

INSERT INTO PUBLIC.REVIEWS (CONTENT, IS_POSITIVE, USER_ID, FILM_ID, USEFUL)
VALUES ('Very bad review', false, 2, 1, 99);

INSERT INTO PUBLIC.REVIEWS (CONTENT, IS_POSITIVE, USER_ID, FILM_ID)
VALUES ('Very good review', true, 3, 1);

INSERT INTO PUBLIC.USERS_REVIEWS (USER_ID, REVIEW_ID, IS_LIKE)
VALUES (1, 3, true);

INSERT INTO PUBLIC.USERS_REVIEWS (USER_ID, REVIEW_ID, IS_LIKE)
VALUES (1, 2, false);